### PR TITLE
SCMFileSystem Error fixed.

### PR DESCRIPTION
**Pull request by gautamabhishek46**
Now this working for bitbucket as well.
I think that we can remove the previous branch name detecting code.

### CODE REVIEW

**Comment by kwhetstone** [comment]
Cool, let's get this merged in.

**Comment by martinda** [comment]
@gautamabhishek46 So the multibranch plugin only looks at the PR branch for the yaml file, do I understand this correctly?

**Comment by gautamabhishek46** [comment]
@martinda At this point, this plugin is working for both PR and normal branches. And I want to keep it this way because users will be able to use it for both PR and normal branches. It can be discussed. What do you say?

**Comment by gautamabhishek46** [comment]
I was asking that, should I keep the functions "getBranchForPR", "getCleanRefSpecs" and "getBranchName" or just remove them.

**Comment by martinda** [comment]
@gautamabhishek46 if code is not needed, remove it.

**Comment by martinda** [comment]
I guess I am not understanding why this works and why the other did not work, i.e. I do not understand what `jenkins.scm.api.mixin.ChangeRequestSCMHead2` truly represents, but this is not important. Let's merge when you are ready @gautamabhishek46

**Pull request merged**
